#!/bin/sh

# May 9, 2011: this script is not used; functionality handled
#              directly by vm-start

# bring up interface and add it to the host-only bridge

VMTOOLSCONF=${VMTOOLSCONF:=/etc}
. ${VMTOOLSCONF}/vm-tools.conf

dev=$1

if [ -z "$dev" ]
then
    echo "usage: ${0##*/} device"
    exit 1
fi

ifconfig $dev 0.0.0.0 up
if [ $? -ne 0 ]
then
    echo "failed to bringup device $dev" >&2
    exit 1
fi

brctl addif $HOSTBR $dev
if [ $? -ne 0 ]
then
    echo "failed to add device $dev to $HOSTBR bridge" >&2
    ifconfig $dev down
    exit 1
fi

if [ -n "$HOSTBR_MTU" ]
then
	ifconfig $dev mtu $HOSTBR_MTU
fi

exit 0
